// <auto-generated />
namespace GoBetGoal_BackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddFilteredIndexToUserNickName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFilteredIndexToUserNickName));
        
        string IMigrationMetadata.Id
        {
            get { return "202508101718256_AddFilteredIndexToUserNickName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
